import = [
	"~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]
shell = "zsh"
working_directory = "/home/ysxbel"
[window]
padding = { x = 35, y = 25 }
[font]
size = 12
[mouse]
bindings = [
	{ mouse = "Middle", Action = "None"  }
	]
