set -g status-style 'bg=colour238 fg=colour246'
set -g status-right '#[fg=colour238,bg=colour180] %d/%m/%y %H:%M:%S'
set -g status-left ''

set -g pane-border-style 'fg=colour217 bg=colour0'
set -g pane-active-border-style 'bg=colour0 fg=colour217'

set-option -g allow-rename off

bind | split-window -h
bind - split-window -v
unbind '"'
unbind %
